#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSPD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SERA_ESS")]
	public partial class ESSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTrxAttendance(TrxAttendance instance);
    partial void UpdateTrxAttendance(TrxAttendance instance);
    partial void DeleteTrxAttendance(TrxAttendance instance);
    partial void InsertTrxCiCo(TrxCiCo instance);
    partial void UpdateTrxCiCo(TrxCiCo instance);
    partial void DeleteTrxCiCo(TrxCiCo instance);
    #endregion
		
		public ESSDataContext() : 
				base(global::eSPD.Properties.Settings.Default.SERA_ESSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ESSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ESSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ESSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ESSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TrxAttendance> TrxAttendances
		{
			get
			{
				return this.GetTable<TrxAttendance>();
			}
		}
		
		public System.Data.Linq.Table<TrxCiCo> TrxCiCos
		{
			get
			{
				return this.GetTable<TrxCiCo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="att.TrxAttendance")]
	public partial class TrxAttendance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Nullable<int> _Nrp;
		
		private string _AttendanceCode;
		
		private System.Nullable<System.DateTime> _BegDa;
		
		private System.Nullable<System.DateTime> _EndDa;
		
		private System.Nullable<System.DateTime> _CreDa;
		
		private string _Status;
		
		private string _Reason;
		
		private System.Nullable<System.DateTime> _AppRejDa;
		
		private string _DestApp;
		
		private string _AppRejBy;
		
		private System.Nullable<System.DateTime> _SAPSentDt;
		
		private System.Nullable<System.DateTime> _SAPSucceedDt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNrpChanging(System.Nullable<int> value);
    partial void OnNrpChanged();
    partial void OnAttendanceCodeChanging(string value);
    partial void OnAttendanceCodeChanged();
    partial void OnBegDaChanging(System.Nullable<System.DateTime> value);
    partial void OnBegDaChanged();
    partial void OnEndDaChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDaChanged();
    partial void OnCreDaChanging(System.Nullable<System.DateTime> value);
    partial void OnCreDaChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnAppRejDaChanging(System.Nullable<System.DateTime> value);
    partial void OnAppRejDaChanged();
    partial void OnDestAppChanging(string value);
    partial void OnDestAppChanged();
    partial void OnAppRejByChanging(string value);
    partial void OnAppRejByChanged();
    partial void OnSAPSentDtChanging(System.Nullable<System.DateTime> value);
    partial void OnSAPSentDtChanged();
    partial void OnSAPSucceedDtChanging(System.Nullable<System.DateTime> value);
    partial void OnSAPSucceedDtChanged();
    #endregion
		
		public TrxAttendance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nrp", DbType="Int")]
		public System.Nullable<int> Nrp
		{
			get
			{
				return this._Nrp;
			}
			set
			{
				if ((this._Nrp != value))
				{
					this.OnNrpChanging(value);
					this.SendPropertyChanging();
					this._Nrp = value;
					this.SendPropertyChanged("Nrp");
					this.OnNrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceCode", DbType="VarChar(10)")]
		public string AttendanceCode
		{
			get
			{
				return this._AttendanceCode;
			}
			set
			{
				if ((this._AttendanceCode != value))
				{
					this.OnAttendanceCodeChanging(value);
					this.SendPropertyChanging();
					this._AttendanceCode = value;
					this.SendPropertyChanged("AttendanceCode");
					this.OnAttendanceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BegDa", DbType="DateTime")]
		public System.Nullable<System.DateTime> BegDa
		{
			get
			{
				return this._BegDa;
			}
			set
			{
				if ((this._BegDa != value))
				{
					this.OnBegDaChanging(value);
					this.SendPropertyChanging();
					this._BegDa = value;
					this.SendPropertyChanged("BegDa");
					this.OnBegDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDa", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDa
		{
			get
			{
				return this._EndDa;
			}
			set
			{
				if ((this._EndDa != value))
				{
					this.OnEndDaChanging(value);
					this.SendPropertyChanging();
					this._EndDa = value;
					this.SendPropertyChanged("EndDa");
					this.OnEndDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreDa", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreDa
		{
			get
			{
				return this._CreDa;
			}
			set
			{
				if ((this._CreDa != value))
				{
					this.OnCreDaChanging(value);
					this.SendPropertyChanging();
					this._CreDa = value;
					this.SendPropertyChanged("CreDa");
					this.OnCreDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(255)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppRejDa", DbType="DateTime")]
		public System.Nullable<System.DateTime> AppRejDa
		{
			get
			{
				return this._AppRejDa;
			}
			set
			{
				if ((this._AppRejDa != value))
				{
					this.OnAppRejDaChanging(value);
					this.SendPropertyChanging();
					this._AppRejDa = value;
					this.SendPropertyChanged("AppRejDa");
					this.OnAppRejDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestApp", DbType="VarChar(100)")]
		public string DestApp
		{
			get
			{
				return this._DestApp;
			}
			set
			{
				if ((this._DestApp != value))
				{
					this.OnDestAppChanging(value);
					this.SendPropertyChanging();
					this._DestApp = value;
					this.SendPropertyChanged("DestApp");
					this.OnDestAppChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppRejBy", DbType="VarChar(100)")]
		public string AppRejBy
		{
			get
			{
				return this._AppRejBy;
			}
			set
			{
				if ((this._AppRejBy != value))
				{
					this.OnAppRejByChanging(value);
					this.SendPropertyChanging();
					this._AppRejBy = value;
					this.SendPropertyChanged("AppRejBy");
					this.OnAppRejByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPSentDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAPSentDt
		{
			get
			{
				return this._SAPSentDt;
			}
			set
			{
				if ((this._SAPSentDt != value))
				{
					this.OnSAPSentDtChanging(value);
					this.SendPropertyChanging();
					this._SAPSentDt = value;
					this.SendPropertyChanged("SAPSentDt");
					this.OnSAPSentDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPSucceedDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAPSucceedDt
		{
			get
			{
				return this._SAPSucceedDt;
			}
			set
			{
				if ((this._SAPSucceedDt != value))
				{
					this.OnSAPSucceedDtChanging(value);
					this.SendPropertyChanging();
					this._SAPSucceedDt = value;
					this.SendPropertyChanged("SAPSucceedDt");
					this.OnSAPSucceedDtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cico.TrxCiCo")]
	public partial class TrxCiCo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private int _Nrp;
		
		private string _Type;
		
		private string _SubmitType;
		
		private System.DateTime _Time;
		
		private string _DestUser1;
		
		private string _WFStatus;
		
		private string _Reason;
		
		private string _DestUser1UpdateBy;
		
		private System.Nullable<System.DateTime> _DestUser1UpdateDt;
		
		private System.DateTime _CreateDt;
		
		private System.Nullable<System.DateTime> _SapSentDt;
		
		private string _ModifyBy;
		
		private System.Nullable<System.DateTime> _SapSucceedDt;
		
		private string _RemoveFlag;
		
		private string _TerminalID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNrpChanging(int value);
    partial void OnNrpChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnSubmitTypeChanging(string value);
    partial void OnSubmitTypeChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    partial void OnDestUser1Changing(string value);
    partial void OnDestUser1Changed();
    partial void OnWFStatusChanging(string value);
    partial void OnWFStatusChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnDestUser1UpdateByChanging(string value);
    partial void OnDestUser1UpdateByChanged();
    partial void OnDestUser1UpdateDtChanging(System.Nullable<System.DateTime> value);
    partial void OnDestUser1UpdateDtChanged();
    partial void OnCreateDtChanging(System.DateTime value);
    partial void OnCreateDtChanged();
    partial void OnSapSentDtChanging(System.Nullable<System.DateTime> value);
    partial void OnSapSentDtChanged();
    partial void OnModifyByChanging(string value);
    partial void OnModifyByChanged();
    partial void OnSapSucceedDtChanging(System.Nullable<System.DateTime> value);
    partial void OnSapSucceedDtChanged();
    partial void OnRemoveFlagChanging(string value);
    partial void OnRemoveFlagChanged();
    partial void OnTerminalIDChanging(string value);
    partial void OnTerminalIDChanged();
    #endregion
		
		public TrxCiCo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nrp", DbType="Int NOT NULL")]
		public int Nrp
		{
			get
			{
				return this._Nrp;
			}
			set
			{
				if ((this._Nrp != value))
				{
					this.OnNrpChanging(value);
					this.SendPropertyChanging();
					this._Nrp = value;
					this.SendPropertyChanged("Nrp");
					this.OnNrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SubmitType
		{
			get
			{
				return this._SubmitType;
			}
			set
			{
				if ((this._SubmitType != value))
				{
					this.OnSubmitTypeChanging(value);
					this.SendPropertyChanging();
					this._SubmitType = value;
					this.SendPropertyChanged("SubmitType");
					this.OnSubmitTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestUser1", DbType="VarChar(100)")]
		public string DestUser1
		{
			get
			{
				return this._DestUser1;
			}
			set
			{
				if ((this._DestUser1 != value))
				{
					this.OnDestUser1Changing(value);
					this.SendPropertyChanging();
					this._DestUser1 = value;
					this.SendPropertyChanged("DestUser1");
					this.OnDestUser1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFStatus", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string WFStatus
		{
			get
			{
				return this._WFStatus;
			}
			set
			{
				if ((this._WFStatus != value))
				{
					this.OnWFStatusChanging(value);
					this.SendPropertyChanging();
					this._WFStatus = value;
					this.SendPropertyChanged("WFStatus");
					this.OnWFStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(MAX)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestUser1UpdateBy", DbType="VarChar(100)")]
		public string DestUser1UpdateBy
		{
			get
			{
				return this._DestUser1UpdateBy;
			}
			set
			{
				if ((this._DestUser1UpdateBy != value))
				{
					this.OnDestUser1UpdateByChanging(value);
					this.SendPropertyChanging();
					this._DestUser1UpdateBy = value;
					this.SendPropertyChanged("DestUser1UpdateBy");
					this.OnDestUser1UpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestUser1UpdateDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> DestUser1UpdateDt
		{
			get
			{
				return this._DestUser1UpdateDt;
			}
			set
			{
				if ((this._DestUser1UpdateDt != value))
				{
					this.OnDestUser1UpdateDtChanging(value);
					this.SendPropertyChanging();
					this._DestUser1UpdateDt = value;
					this.SendPropertyChanged("DestUser1UpdateDt");
					this.OnDestUser1UpdateDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDt", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDt
		{
			get
			{
				return this._CreateDt;
			}
			set
			{
				if ((this._CreateDt != value))
				{
					this.OnCreateDtChanging(value);
					this.SendPropertyChanging();
					this._CreateDt = value;
					this.SendPropertyChanged("CreateDt");
					this.OnCreateDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SapSentDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> SapSentDt
		{
			get
			{
				return this._SapSentDt;
			}
			set
			{
				if ((this._SapSentDt != value))
				{
					this.OnSapSentDtChanging(value);
					this.SendPropertyChanging();
					this._SapSentDt = value;
					this.SendPropertyChanged("SapSentDt");
					this.OnSapSentDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="VarChar(50)")]
		public string ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SapSucceedDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> SapSucceedDt
		{
			get
			{
				return this._SapSucceedDt;
			}
			set
			{
				if ((this._SapSucceedDt != value))
				{
					this.OnSapSucceedDtChanging(value);
					this.SendPropertyChanging();
					this._SapSucceedDt = value;
					this.SendPropertyChanged("SapSucceedDt");
					this.OnSapSucceedDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemoveFlag", DbType="VarChar(50)")]
		public string RemoveFlag
		{
			get
			{
				return this._RemoveFlag;
			}
			set
			{
				if ((this._RemoveFlag != value))
				{
					this.OnRemoveFlagChanging(value);
					this.SendPropertyChanging();
					this._RemoveFlag = value;
					this.SendPropertyChanged("RemoveFlag");
					this.OnRemoveFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerminalID", DbType="VarChar(50)")]
		public string TerminalID
		{
			get
			{
				return this._TerminalID;
			}
			set
			{
				if ((this._TerminalID != value))
				{
					this.OnTerminalIDChanging(value);
					this.SendPropertyChanging();
					this._TerminalID = value;
					this.SendPropertyChanged("TerminalID");
					this.OnTerminalIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
