<?xml version="1.0" encoding="utf-8"?><Database Name="SERA_ESS" Class="ESSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sera15013;Initial Catalog=SERA_ESS;Persist Security Info=True;User ID=sa;Application Name=spdnew" SettingsObjectName="eSPD.Properties.Settings" SettingsPropertyName="SERA_ESSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="att.TrxAttendance" Member="TrxAttendances">
    <Type Name="TrxAttendance">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nrp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttendanceCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BegDa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreDa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AppRejDa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DestApp" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AppRejBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SAPSentDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAPSucceedDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="cico.TrxCiCo" Member="TrxCiCos">
    <Type Name="TrxCiCo">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nrp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SubmitType" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DestUser1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WFStatus" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DestUser1UpdateBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DestUser1UpdateDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SapSentDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SapSucceedDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RemoveFlag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TerminalID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>